# Generated by Django 4.1.7 on 2023-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_channels_describe_alter_customer_wechat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
